### ISSUE TITLE
赛博丁真,集合！

### ISSUE THREAD

**Issue by wushaoge** [vietnh1009/ASCII-generator#22]
赛博丁真,集合！

**Comment by liqiao7** [comment]
逗死我了

**Comment by AtomDelta123** [comment]
乐

**Comment by SimonGH0STRiley** [comment]
XD

**Comment by ayyayyayy2002** [comment]
加我一个

**Comment by dongguaguaguagua** [comment]
插眼

**Comment by chengyiqiu1121** [comment]
cy

**Comment by xuejianxianzun** [comment]
难绷

**Comment by neosparrow2024** [comment]
lmao

**Comment by Chen-speculation** [comment]
shouldn't raise issues unrelated to the project within the issue.

**Comment by mnn1127** [comment]
亏我之前还在知乎上面替他辩解过呢，说他虽然视频都是花里胡哨没意义，但是普通人也不会研究很深的科技，大家都是看乐子的，在看乐子这方面何同学做的确实挺好。现在居然用着别人的开源项目接商单，还说是自己做的。自称科技区的up主，居然觉得科技区的粉丝连个github都不知道吧。真混蛋玩意，又蠢又坏。

**Comment by ShuhongDai** [comment]
**打卡**

**Comment by KantLee** [comment]
打卡

**Comment by AvariceZhao** [comment]
打卡

**Comment by deepSpace712** [comment]
笑哭哈哈哈哈哈

**Comment by Rayzheng227** [comment]
笑死我了

**Comment by supernova4869** [comment]
隋唐测验满昏！

**Comment by Xigua7i** [comment]
《乐》《典》

**Comment by TenshGU** [comment]
广告位招租

**Comment by ReallySilverBell** [comment]
慕名而来

**Comment by suzengyi** [comment]
![IMG_0106](https://github.com/user-attachments/assets/28617c05-836d-4b20-99cd-d51dea1e089c)
转自知乎

**Comment by xiang578** [comment]
这次刚开始看的时候觉得还行。。。

**Comment by Charon1997** [comment]
集合！

**Comment by HackerLZH** [comment]
我抄你的码

**Comment by Charon1997** [comment]
hi，我已经收到你的邮件了，我会尽快查看的~

**Comment by SimonGH0STRiley** [comment]
> 我抄你的码

鸡肚你的才华

**Comment by Mq-b** [comment]
https://www.bilibili.com/opus/1001405125842960390?spm_id_from=333.1365.0.0

**Comment by yizhang2077** [comment]
打卡

**Comment by TigerLeee** [comment]
A copy cat steal your code(抄你的码).

![v2-5df692c01391edbea428182889c542d7_1440w](https://github.com/user-attachments/assets/9b38be80-19fb-49bf-bfe2-6315f42f7680)

**Comment by innovationty** [comment]
打卡

**Comment by Jesse205** [comment]
[《GitHub 社区行为准则》](https://docs.github.com/zh/site-policy/github-terms/github-community-code-of-conduct)

...
- 井然有序。 尽可能做到物归其位，以便我们减少整理时间，将更多的时间花在讨论上。 因此：
    - 不要在错误的类别中开始讨论。
    - 不要在多个讨论中交叉发布同样的内容。
    - 不要发布无意义回复。
    - 除非您有新的相关信息要分享，否则不要贸然发帖。
    - 不要中途转换讨论。
使用赞成按钮，而不要发布“+1”或“同意”。 不要将现有讨论带到完全不同的方向，这种情况应该开启一个新讨论。

**Comment by Minstdfx** [comment]
👀

**Comment by Canmi21** [comment]
插眼

**Comment by ChineseDictionary** [comment]
第一时间前来围观

**Comment by 8824PPZ** [comment]
> > 我抄你的码
> 
> 鸡肚你的才华

逗死我了

**Comment by kukemc** [comment]
很乐，但在github上issue是给项目提交正经问题的地方，这种内容不应当发在仓库的issue中

**Comment by CyanChanges** [comment]
请**不要**继续创建这种与项目无关 Issue
Please **DO NOT** create more meaningless issue.

**Comment by CSfufu** [comment]
cybd

**Comment by coder-wangbin** [comment]
![image](https://github.com/user-attachments/assets/dd4af3c6-5889-4c40-b2e0-59b0c30f1fdf)

**Comment by fntp** [comment]
我对视频博主并不关心是谁，我只关心开源项目被盗用却不指出引用出处。我是非常痛恨这种行为的，跟小偷有什么两样？中国是一个讲究道德品德的国家，是一个注重个人内在的国家，这个博主的无耻行径显然是与传统文化背道而驰，我大概浏览了一下这个人的视频作品，花里胡哨的噱头不少，真材实料的水平不多。所以，有这种行为我分析应该是惯犯，只不过这次偷了懒，忘了遮住必要元素，说审稿不严其实是说自己忘了审核能不能看出来是抄袭的了，它的作品风格自己可以去看看，哪一个视频不是视觉效果>实际业内水平的，中国有一个词叫华而不实，哗众取宠，没错，说的就是这种人。
我一般是不想评论外界的，但是我看到拿开源项目恰烂饭的SB我就无法容忍这一点，不尊重别人的劳动成功，指出一下是借鉴别人的很难吗？你怎么做你的视频我并不关心，别他妈恰烂饭恶心开源的人心态！！！


---双语版来自百度翻译
I don't care who the video blogger is, I only care about open source projects being hacked without pointing out the source of the citation. I hate this kind of behavior very much. What's the difference between it and a thief? China is a country that values moral character and values individual inner qualities. The shameless behavior of this blogger is obviously contrary to traditional culture. I have probably browsed through this person's video works, and there are many flashy gimmicks, but the level of genuine materials is not high. So, in my analysis, this kind of behavior should be a habitual offender, but this time they were lazy and forgot to cover up necessary elements. Saying that the review was not strict actually means that they forgot whether the review could tell that it was plagiarism. You can check the style of their works yourself. Which video is not visually stunning>the actual industry level? In China, there is a term called "flashy but impractical", which refers to this kind of person.
I usually don't want to comment on the outside world, but when I see SB taking advantage of open source projects, I can't tolerate it. They don't respect the success of others' labor. Is it difficult to learn from others? I don't care how you do your video. Don't be a his mother disgusting open-source person

**Comment by LFMJUN** [comment]
cy

**Comment by CyanChanges** [comment]
> cy

> GitHub Community Code of Conduct
> Don’t post no-content replies.

你可以点击右侧的 `Subscribe` 按钮来获得消息推送, 而不是发送一条 插眼 评论
You can use the `Subscribe` button on the right, instead of adding meaningless comment for message notifications.

**Comment by 123avd** [comment]
请**关闭**这条无意义的 issue

**Comment by KirsminX** [comment]
Posting irrelevant content in an Issue is a low-quality behavior and not advisable. While the video author may have made mistakes, you shouldn't vent your righteous indignation in the Issue, as this can cause trouble for the repository owner.

**Comment by YF1313** [comment]
打卡

**Comment by Ariana-Yang** [comment]
引用丁真，鉴定为抄他的码

**Comment by Robinsssson** [comment]
请关闭这个仓库，每一份无意义的回复和低质量的issue都会给仓库持有者造成不必要的困扰

Please close this issue. Every meaningless response and low-quality issue creates unnecessary trouble for the repository owner.

**Comment by DYMS-212** [comment]
一开源，就字硏

**Comment by wushaoge** [comment]
> 请关闭这个仓库，每一份无意义的回复和低质量的issue都会给仓库持有者造成不必要的困扰
> 
> Please close this issue. Every meaningless response and low-quality issue creates unnecessary trouble for the repository owner.

别搁这当赛博警察，我们能发声的至少还都是看不起赛博丁真，能让作者知道自己项目被抄袭了，假设大家没一个人提issue，作者的成果就这样被人白嫖了？
你搁这站道德制高点谴责我们？难道你不应该发挥你键盘侠的功力去喷丁真么？别天天装圣母、白莲花

**Comment by wednesday** [comment]
> > 请关闭这个仓库，每一份无意义的回复和低质量的issue都会给仓库持有者造成不必要的困扰
> > Please close this issue. Every meaningless response and low-quality issue creates unnecessary trouble for the repository owner.
> 
> 别搁这当赛博警察，我们能发声的至少还都是看不起赛博丁真，能让作者知道自己项目被抄袭了，假设大家没一个人提issue，作者的成果就这样被人白嫖了？ 你搁这站道德制高点谴责我们？难道你不应该发挥你键盘侠的功力去喷丁真么？别天天装圣母、白莲花

简中特色

**Comment by Robinsssson** [comment]
> > 请关闭这个仓库，每一份无意义的回复和低质量的issue都会给仓库持有者造成不必要的困扰
> > 
> > Please close this issue. Every meaningless response and low-quality issue creates unnecessary trouble for the repository owner.
> 
> 别搁这当赛博警察，我们能发声的至少还都是看不起赛博丁真，能让作者知道自己项目被抄袭了，假设大家没一个人提issue，作者的成果就这样被人白嫖了？
> 你搁这站道德制高点谴责我们？难道你不应该发挥你键盘侠的功力去喷丁真么？别天天装圣母、白莲花

作者已经知道并回复了，移步#25就能看到，无意义的刷屏和骂人只能彰显你的素质

**Comment by CyanChanges** [comment]
@vietnh1009 may you close this issue and lock it as spam?

**Comment by Starcrackeriii** [comment]
移源笑传之抄抄码🤣🤣

**Comment by quibbler01** [comment]
开源史上里程碑事件
