### ISSUE TITLE
何xx声明，绝对没有抄，我是下载的，因为我不太会git clone

### ISSUE THREAD

**Issue by wenhainan** [vietnh1009/ASCII-generator#24]

**Comment by supernova4869** [comment]
因为不会用git clone，只好直接下载，在Downloads里运行

**Comment by TutuchanXD** [comment]
何扩散到github里来了？

**Comment by Sharpiless** [comment]
慕名而来😂

**Comment by xuejianxianzun** [comment]
要说他不会用GitHub还真有可能🤣

**Comment by Xigua7i** [comment]
难绷

**Comment by xiang578** [comment]
xiaobu 背锅，老板让他实现一个，谁知道他抄了一个。。。

**Comment by AndyJinSS** [comment]
绷不住

**Comment by cyamoyed** [comment]
哈哈哈哈哈哈哈太搞笑了，代码运行都是在Downloads文件夹下

**Comment by GonnaBeOk-zzt** [comment]
慕名而来，老哥也是好起来了，能吃上赛博丁真的饭你就感恩吧

**Comment by Sou1ReaPer** [comment]
太乐了🤣

**Comment by CyanChanges** [comment]
请不要开和项目无直接相关的 Issue
Please **DO NOT** open meaningless issues.

**Comment by kukemc** [comment]
Github的Issue不是评论区也不是贴吧，不要在这随地大小便

**Comment by ShinChven** [comment]
请关闭这个没有意义的issue。

**Comment by yangyunbin** [comment]
电脑开个VPN Git不用单独设置代理也能拉下来的

**Comment by Timeon1** [comment]
因崔斯汀

**Comment by theOnlyUnique** [comment]
让我想起了之前比赛中，我通过别人的git记录查到了别人抄袭我作品的证据。
有点异曲同工哈哈哈，本质上是git玩太菜了🤣🤣🤣

**Comment by ainiyiwan** [comment]
[从何同学被指盗用开源项目谈国人对于开源的意识](https://mp.weixin.qq.com/s/7MBl1-CVfgXWSK4SIKecLQ)

**Comment by theOnlyUnique** [comment]
> [从何同学被指盗用开源项目谈国人对于开源的意识](https://mp.weixin.qq.com/s/7MBl1-CVfgXWSK4SIKecLQ)

我以为你这文章是要呼吁人们去了解开源的规矩呢。。。

**Comment by theOnlyUnique** [comment]
> > 让我想起了之前比赛中，我通过别人的git记录查到了别人抄袭我作品的证据。 有点异曲同工哈哈哈，本质上是git玩太菜了🤣🤣🤣
> 
> ## ![image](https://private-user-images.githubusercontent.com/115192496/387933171-0e812fc1-2ae6-4e53-ab6a-d7922a2d8b27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzcxMjIsIm5iZiI6MTczMjA3NjgyMiwicGF0aCI6Ii8xMTUxOTI0OTYvMzg3OTMzMTcxLTBlODEyZmMxLTJhZTYtNGU1My1hYjZhLWQ3OTIyYTJkOGIyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQwNDI3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjc1OTliOTFkYzI4NTNkZGRhNDE3MGQ1ZjQ4MjQ5Y2I3NmY4NmY0NDYxZmJiZTAwYWU5MWQ5MGEyNmQ5M2ExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CgYrEgzQ187s8QRhFwBbRQfX2qdQaV_4iI4qMvQsL7Y)
> ### 哥们，你自己的git隐私都没做好

额，这个没什么大用，开盒很简单的。主要是方便别人联系我，我自己做的开源为啥还要藏起来。。

**Comment by migeyusu** [comment]
> 因为不会用git clone，只好直接下载，在Downloads里运行

6，还真是

**Comment by quibbler01** [comment]
我称之为视频剪辑大师
