### ISSUE TITLE
何同学已道歉！！必须要求它把视频收入全部捐给此项目！！！

### ISSUE THREAD

**Issue by ywh555hhh** [vietnh1009/ASCII-generator#26]
<img width="729" alt="image" src="https://github.com/user-attachments/assets/7c4beb4b-d7d0-4125-94bc-16d4479c61cf">

道歉是没用的，必须把钱吐出来

**Comment by KINGFIOX** [comment]
![image](https://github.com/user-attachments/assets/a4a9f63e-bfbb-464b-bab3-d0742a69c988)

**Comment by xuejianxianzun** [comment]
紧急换源，但依然不愿意在视频简介里加上开源项目地址😄

**Comment by View12138** [comment]
<img width="778" alt="Snipaste_20241119_150938" src="https://github.com/user-attachments/assets/909a213b-e906-4153-8cc2-dd8abf2159a1">
这是之前的视频对比截图

**Comment by CyanChanges** [comment]
太不严谨了, 被发现是抄的了, 名字都没改
Too imprecise. Get exposed they are plagiarized open source projects, even without renaming it.

下次别忘了改文件名和重命名变量
Don't forget rename files and variables next time.

**Comment by losehu** [comment]
賽博丁真の涙
建议标题改为“賽博丁真”

**Comment by 0x0129** [comment]
开源软件最大受益者。

**Comment by windshadow233** [comment]
道歉❌
公关✅
没人指出来它就会蒙混过关

**Comment by RunningKuma** [comment]
很乐，但在github上issue是给项目提交正经问题的地方，这种内容不应当发在仓库的issue中

**Comment by 0x0129** [comment]
是这样的发自我的 iPhone在 2024年11月19日，16:51，Boning Xiao ***@***.***> 写道：﻿
很乐，但在github上issue是给项目提交正经问题的地方，这种内容不应当发在仓库的issue中
