### ISSUE TITLE
亲爱的何同学，你在哪儿？

### ISSUE THREAD

**Issue by jsma-1999** [vietnh1009/ASCII-generator#27]

**Comment by kukemc** [comment]
在那一个issue说说就行了，别搞那么多issue影响别人正常提issue

**Comment by Jesse205** [comment]
[《GitHub 社区行为准则》](https://docs.github.com/zh/site-policy/github-terms/github-community-code-of-conduct)

...
- 井然有序。 尽可能做到物归其位，以便我们减少整理时间，将更多的时间花在讨论上。 因此：
    - 不要在错误的类别中开始讨论。
    - 不要在多个讨论中交叉发布同样的内容。
    - 不要发布无意义回复。
    - 除非您有新的相关信息要分享，否则不要贸然发帖。
    - 不要中途转换讨论。
使用赞成按钮，而不要发布“+1”或“同意”。 不要将现有讨论带到完全不同的方向，这种情况应该开启一个新讨论。
...

**Comment by kukemc** [comment]
请关闭此issue
