### ISSUE TITLE
如何看待何同学的道歉声明

### ISSUE THREAD

**Issue by CSfufu** [vietnh1009/ASCII-generator#29]
![WechatIMG4736](https://github.com/user-attachments/assets/6cd9593e-ec35-4102-8222-5afdf15a1959)

**Comment by yin2hao** [comment]
没有诚意，评论区已经被阿瓦隆发不了评论了。
还有就是提醒开发者项目被盗用可以，但这种无关的issues还是不要打扰开发者了

**Comment by cyamoyed** [comment]
兄弟把这儿当知乎提问呢

**Comment by DuolaD** [comment]
对不起，我错了，下次还敢。

**Comment by chengnan049** [comment]
如何看待这种行为？
[GitHub 社区行为准则](https://docs.github.com/zh/site-policy/github-terms/github-community-code-of-conduct)
**井然有序**。 
尽可能做到物归其位，以便我们减少整理时间，将更多的时间花在讨论上。 因此：

不要在错误的类别中开始讨论。
不要在多个讨论中交叉发布同样的内容。
不要发布无意义回复。
除非您有新的相关信息要分享，否则不要贸然发帖。
不要中途转换讨论。
使用赞成按钮，而不要发布“+1”或“同意”。 不要将现有讨论带到完全不同的方向，这种情况应该开启一个新讨论。

**Comment by fntp** [comment]
我并不关心视频博主是谁，我只关心开源项目被盗用却不指出引用出处这个问题。我是非常痛恨这种行为的，跟小偷有什么两样？中国是一个讲究道德品德的国家，是一个注重个人内在的国家，这个博主的无耻行径显然是与传统文化背道而驰，我大概浏览了一下这个人的视频作品，花里胡哨的噱头不少，真材实料的水平不多。所以，有这种行为我分析应该是惯犯，只不过这次偷了懒，忘了遮住必要元素，说审稿不严其实是说自己忘了审核能不能看出来是抄袭的了，它的作品风格自己可以去看看，哪一个视频不是视觉效果>实际业内水平的，中国有一个词叫华而不实，哗众取宠，没错，说的就是这种人。
我一般是不想评论外界的，但是我看到拿开源项目恰烂饭的SB我就无法容忍这一点，不尊重别人的劳动成果，指出一下是借鉴别人的很难吗？你怎么做你的视频我并不关心，别他妈恰烂饭恶心开源的人心态！！！

---双语版来自百度翻译
I don't care who the video blogger is, I only care about open source projects being hacked without pointing out the source of the citation. I hate this kind of behavior very much. What's the difference between it and a thief? China is a country that values moral character and values individual inner qualities. The shameless behavior of this blogger is obviously contrary to traditional culture. I have probably browsed through this person's video works, and there are many flashy gimmicks, but the level of genuine materials is not high. So, in my analysis, this kind of behavior should be a habitual offender, but this time they were lazy and forgot to cover up necessary elements. Saying that the review was not strict actually means that they forgot whether the review could tell that it was plagiarism. You can check the style of their works yourself. Which video is not visually stunning>the actual industry level? In China, there is a term called "flashy but impractical", which refers to this kind of person.
I usually don't want to comment on the outside world, but when I see SB taking advantage of open source projects, I can't tolerate it. They don't respect the success of others' labor. Is it difficult to learn from others? I don't care how you do your video. Don't be xxx disgusting open-source person

**Comment by SivanRen** [comment]
丁真确实比他纯真

**Comment by kukemc** [comment]
issue不是知乎也不是评论区 不要发送这种无意义内容

**Comment by nh34546** [comment]
没用

**Comment by xzhingithub** [comment]
脑子有坑？把这当知乎了？要发问去知乎，没人拦你，issue是给你这么用的？！

**Comment by CyanChanges** [comment]
@vietnh1009 may you close and lock the conversation?

**Comment by ainiyiwan** [comment]
[从何同学被指盗用开源项目谈国人对于开源的意识](https://mp.weixin.qq.com/s/7MBl1-CVfgXWSK4SIKecLQ)

**Comment by u1s3-fu** [comment]
您的issue不符合GitHub Community Code of Conduct的精神，重复的内容可能会打扰到开发者并给开发者带来困扰（issue会通过email通知开发者）
请转移到 #25 去讨论此事，并关闭此issue
