### ISSUE TITLE
我用36万行备忘录做了个动画…

### ISSUE THREAD

**Issue by MarsTLBAD** [vietnh1009/ASCII-generator#32]
老师好我叫何同学
(https://space.bilibili.com/163637592)

置顶 
我们看到了大家在评论中关于字符画转制程序的讨论。我们视频中使用的字符转制程序确实是由开源项目ASCII-generator改动而来，改动的内容主要是优化字符生成比例、图片裁切方式和传参方式。视频中55秒的旁白“所以我们专门写了一个软件，可以把预览动画里的色块转换成字符”确实不严谨，非常抱歉在视频里没有指出这一点。之所以会出现这种情况，是因为我在写视频的文案时不够严谨，没有和相关同事做好沟通，并没有意识到这个程序是从开源程序改动而来，也没有尽到审稿义务，实在抱歉。我们已经对视频进行换源，修改了相关描述并增加引用来源，同时进行内部检讨，反思流程和审稿上的问题。衷心感谢大家的监督。
    5小时前    IP属地：浙江
点赞250
   回复

epcdiy
(https://space.bilibili.com/12590)
请问删除原作者名字是无意识的吗？
    5小时前    IP属地：福建
点赞3104
    回复

**Comment by kukemc** [comment]
不要在用issue发表无意义内容了，这种行为不比何同学好多少

**Comment by FeletexGee** [comment]
在这里刷何搞何扩散也是有碍观瞻。懒得喷

**Comment by SloaAya** [comment]
nbcs 谁关心那个小丑？

**Comment by CyanChanges** [comment]
@vietnh1009 this issue is a duplicate of #25 , please lock the conversation

**Comment by ainiyiwan** [comment]
[从何同学被指盗用开源项目谈国人对于开源的意识](https://mp.weixin.qq.com/s/7MBl1-CVfgXWSK4SIKecLQ)

**Comment by xBoyMinemc** [comment]
借楼，二楼有鬼图

**Comment by Lumine2024** [comment]
请遵守何不扩散条约谢谢喵

**Comment by MyXiaoXi** [comment]
本来都不想登录账号的评论的！但是这人我第一眼看着就很恶心，就是那种超贱的模样。然后我发现一件事，中国大多数人都不是专业的，而何某就是抓住这点，大量无脑好评+少量专业差评的模式，成就了他现在的自己！专业的人是少数的，不好圈钱，但是围观吃瓜的人是多数的
