### ISSUE TITLE
建群，大家想想办法怎么制裁他们这些骗人的

### ISSUE THREAD

**Issue by sudo888samewick** [vietnh1009/ASCII-generator#34]
如果我们只在网上骂一骂，对他们完全没有影响。不能放任他们，我们必须集合起来，一起讨论一下，怎么制裁他们

![image](https://github.com/user-attachments/assets/7a804d2b-93f2-40bb-994f-55964f8ea97a)

**Comment by kukemc** [comment]
这里不是贴吧也不是评论区，Github的issue是让正经反馈项目问题的地方
不要在这里灌水 打扰原项目开发者以及其他正常反馈issue的用户

**Comment by chmod777john** [comment]
> 这里不是贴吧也不是评论区，Github的issue是让正经反馈项目问题的地方 不要在这里灌水 打扰原项目开发者以及其他正常反馈issue的用户

和事佬思想不可取，大家都闭嘴不谈，只会让原作者更加受害。没人规定过 github issue 的用法，技术 issue 是 issue，版权 issue 就不是 issue 了？

**Comment by kukemc** [comment]
> 和事佬思想不可取，大家都闭嘴不谈，只会让原作者更加受害。技术 issue 是 issue，版权 issue 就不是 issue 了？

https://github.com/vietnh1009/ASCII-generator/issues/22#issuecomment-2484816474

**Comment by kukemc** [comment]
以及 https://github.com/vietnh1009/ASCII-generator/issues/25 这才是提 issue 提醒原作者的正确方式

**Comment by XokoukioX** [comment]
关掉吧 你这个也不符合规范

**Comment by CyanChanges** [comment]
@vietnh1009 this issue is meaningless, may you lock it as spam

**Comment by vietnh1009** [comment]
Hi guys, please go to #25 or #23 for further discussion
