### ISSUE TITLE
你们不觉得很酷吗？作为一个理工男，我觉得这实在是太酷了！

### ISSUE THREAD

**Issue by messywind** [vietnh1009/ASCII-generator#36]

**Comment by justwowyeah** [comment]
请先提高自己的道德水平，关闭该issue，然后移步到 #25 。
已经有太多毫无意义、只会带来打扰和争吵的issue。

**Comment by CyanChanges** [comment]
Stop create meaningless issue!!!
@vietnh1009 please close and lock the conversation
