### ISSUE TITLE
这玩意很早之前就玩过了，19年那会读书，这么旧的东西也能抄袭吗？

### ISSUE THREAD

**Issue by ikun-404** [vietnh1009/ASCII-generator#38]
![4312374d1bf2a538773be7414ae09b5](https://github.com/user-attachments/assets/d01a051f-b6f7-43ad-a0c4-2b9d887bde41)

**Comment by xingwangzhe** [comment]
please close it
do not disturb the author

**Comment by 0xarch** [comment]
Not related to origin repository.
