### ISSUE TITLE
我觉得不必要开这么多 Issues 去污染这个项目，后面来的人不要再起新 Issue 了，真想讨论直接在一个 Issue 里发表下自己想法就好了

### ISSUE THREAD

**Issue by alindas** [vietnh1009/ASCII-generator#44]

**Comment by CyanChanges** [comment]
就是说已经有一个了, 现在又来一个...
Already one in https://github.com/vietnh1009/ASCII-generator/issues/35
not again...

**Comment by ainiyiwan** [comment]
[从何同学被指盗用开源项目谈国人对于开源的意识](https://mp.weixin.qq.com/s/7MBl1-CVfgXWSK4SIKecLQ)

**Comment by CyanChanges** [comment]
> [从何同学被指盗用开源项目谈国人对于开源的意识](https://mp.weixin.qq.com/s/7MBl1-CVfgXWSK4SIKecLQ)

又发一遍? 想火想疯了？
spam this article again? You want to be popular as Hetongxue?

**Comment by Lzforevr** [comment]
BV1BfSNYkEMT
一针见血！
A direct hit from gaotiantian, though He has change the source of that video！

**Comment by bioinfotec** [comment]
所以你这个issues其实也没有必要开的...

**Comment by ReSatori** [comment]
所以请关闭你的issues
去 https://github.com/vietnh1009/ASCII-generator/issues/35

**Comment by NpTIme** [comment]
Close 了吧,差不多结束了, 以后再来的都记得骂骂

**Comment by chaseSpace** [comment]
现在看到中文 issue标题，犯恶心了。。

**Comment by chaseSpace** [comment]
我们真的很多搅屎棍，OP赶紧关了，不想火的话。

**Comment by chaolucky18** [comment]
关了，你这行为和一边随地吐痰一边说不要随地吐痰有什么区别
