### ISSUE TITLE
赛博丁真是这样的，前几年吹5g菊花把菊花吹爽了，5g最大受益者

### ISSUE THREAD

**Issue by somebodyway** [vietnh1009/ASCII-generator#46]

**Comment by cdc12345** [comment]
您的issue不符合GitHub Community Code of Conduct的精神
请转移到#25去讨论此事，并关闭此issue

**Comment by RunningKuma** [comment]
您的issue不符合GitHub Community Code of Conduct的精神
请转移到 https://github.com/vietnh1009/ASCII-generator/issues/25 去讨论此事，并关闭此issue

**Comment by huanli233** [comment]
您的issue不符合GitHub Community Code of Conduct的精神，重复的内容可能会打扰到开发者并给开发者带来困扰（issue会通过email通知开发者）
请转移到#25去讨论此事，并关闭此issue

**Comment by CyanChanges** [comment]
您的 Issue 不符合GitHub Community Code of Conduct的精神，重复的内容可能会打扰到开发者并给开发者带来困扰（issue会通过email通知开发者）
请转移到 #25 去讨论此事，并关闭此Issue
另外, 您的 Issue 中包含潜在的色情内容, 我会将其举报给 GitHub Support, 感谢您的支持

**Comment by NiuBoss123** [comment]
您的issue不符合GitHub Community Code of Conduct的精神
请转移到 #25  去讨论此事，并关闭此issue

**Comment by chy669086** [comment]
您的issue不符合GitHub Community Code of Conduct的精神
请转移到 https://github.com/vietnh1009/ASCII-generator/issues/25 去讨论此事，并关闭此issue

**Comment by somebodyway** [comment]
赛博丁真花了多少钱啊的水军真多

**Comment by cdc12345** [comment]
> 赛博丁真花了多少钱啊的水军真多

很乐呵，你转移到 #25 去骂何同学不照样是骂？

**Comment by huanli233** [comment]
> 赛博丁真花了多少钱啊的水军真多

如果您在 #25 发表您的观点与评价我将不会反对。但您在 Github Issues 发表重复的 Issue 会打扰开发者，并且影响到开发者对项目的工作。
如果您仍然将在这些 Issue 下让 Author 关闭 Issue 的人打为水军，那我无话可说。毕竟盗开源项目还能请来这么多创建了不短时间的有仓库、有代码贡献的 Github 账号当水军也是挺厉害的。

**Comment by somebodyway** [comment]
> > 赛博丁真花了多少钱啊的水军真多
> 
> 绷不住了，你在这里发被骚扰的又不是何同学，是原作者
> 
> **把这当何同学的的存储库了是吧**

你猜猜在逼站发，赛博丁真会不会拉黑你，这里看的人最多

**Comment by huanli233** [comment]
> > > 赛博丁真花了多少钱啊的水军真多
> > 
> > 
> > 绷不住了，你在这里发被骚扰的又不是何同学，是原作者
> > **把这当何同学的的存储库了是吧**
> 
> 你猜猜在逼站发，赛博丁真会不会拉黑你，这里看的人最多

然而赛博丁真也不会看这里。你这么做只是骚扰开发者和影响它的项目。更何况已经有了此事相关的 Issue

**Comment by NiuBoss123** [comment]
> > > 赛博丁真花了多少钱啊的水军真多
> > 
> > 
> > 绷不住了，你在这里发被骚扰的又不是何同学，是原作者
> > **把这当何同学的的存储库了是吧**
> 
> 你猜猜在逼站发，赛博丁真会不会拉黑你，这里看的人最多

这里看的人最多，所以一定要在这里开那么多issue骚扰原作者吗？更何况何同学，或者说他们团队会来看这些issue吗？

现在是原作者被骚扰了好吧

**Comment by li126com** [comment]
你跟何同学一个德行
