### ISSUE TITLE
Sorry to disturb you

### ISSUE THREAD

**Issue by zy2324** [vietnh1009/ASCII-generator#47]
Hi vietnh, the reason why this project has some Chinese issue:
     On a video website in China, a popular author posted their latest video, which mentioned your project. However, the video author claimed to have written their own program, which was later discovered by netizens as an open-source project. As a result, netizens were very angry.

**Comment by huanli233** [comment]
您的issue不符合GitHub Community Code of Conduct的精神，重复的内容可能会打扰到开发者并给开发者带来困扰
请转移到#25去讨论此事，并关闭此issue
Your issue does not comply with the spirit of the GitHub Community Code of Conduct. Duplicate content may disturb and cause trouble to developers. 
Please move to #25 to discuss this matter and close this issue.

**Comment by CyanChanges** [comment]
Not again, what you are doing is disturbing the author with a new issue
*1 issue => 1 email for the author
