### ISSUE TITLE
北邮之耻

### ISSUE THREAD

**Issue by 1625369372** [vietnh1009/ASCII-generator#48]
怎么敢在之前的视频里卖情怀的，tm开源代码都能偷？真以为回学校演讲校友把你当人看？
回学校找校友帮忙一分钱不给还好意思标榜为爱发电，本科绩点后20%的天才科技博主？

**Comment by YUCLing** [comment]
Duplicate of #25.

**Comment by NiuBoss123** [comment]
您的issue不符合GitHub Community Code of Conduct的精神，重复的内容可能会打扰到开发者并给开发者带来困扰（issue会通过email通知开发者）
请转移到 #25 去讨论此事，并关闭此issue

**Comment by quibbler01** [comment]
何同学视频特效做的还是可以的，硬贴金搞这些。真没什么科技含量，科技感到是拉满了。很会做PPT的一类人。
