### ISSUE TITLE
Solution to heated topic on this repository

### ISSUE THREAD

**Issue by YUCLing** [vietnh1009/ASCII-generator#49]
Hi, I feel so sorry that your repository is being spamed due to an unrelated topic. This issue aimed to provide an idea to help you from being disturbed.

I suggest you to enable the interaction limits on this repository. You can follow the link below to do so:

https://github.com/vietnh1009/ASCII-generator/settings/interaction_limits

You'd better use the `Limit to prior contributors` option or a more strict one, and enable it for one week or longer as you prefer.

Again, sorry for disturbing

**Comment by MaXiaoYang6** [comment]
你的事儿真多

**Comment by yqs112358** [comment]
@vietnh1009

**Comment by CyanChanges** [comment]
I suggest also delete those dumb issues.
建议也把那些没过脑子的垃圾 issue 也删了

**Comment by RexWzh** [comment]
I hope the author isn't offended or biased against Chinese developers.

A positive perspective: **The incident demonstrates the project's excellence, attracting new contributions aimed at improvement and compatibility.**

The spam issues mainly come from users unfamiliar with open source. A similar situation occurred when Elon open-sourced the Grok model, drawing non-developers eager to share their thoughts.

Most Chinese developers follow guidelines, and many are working to reduce the negative impact. There are many projects such as OSPP, promoting open-source culture in China. However, some people still have insufficient understanding about open source, equating it with free source.
