### ISSUE TITLE
生物多樣性/Biodiversity

### ISSUE THREAD

**Issue by codeNiuMa** [vietnh1009/ASCII-generator#51]
[生物多樣性](https://zh.wikipedia.org/wiki/%E7%94%9F%E7%89%A9%E5%A4%9A%E6%A8%A3%E6%80%A7)
[Biodiversity](https://en.wikipedia.org/wiki/Biodiversity)
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Charles_Darwin%2C_English_naturlist%2C_colored.jpg/330px-Charles_Darwin%2C_English_naturlist%2C_colored.jpg">

**Comment by mark-jiang-1470** [comment]
您的 Issue 不符合 GitHub Community Code of Conduct 的精神，重复的内容可能会打扰到开发者并给开发者带来困扰（Issue 会通过 email 通知开发者）
请转移到 https://github.com/vietnh1009/ASCII-generator/issues/25 去讨论此事，并关闭此 Issue
Your issue does not comply with the spirit of the GitHub Community Code of Conduct. Duplicate content may disturb and cause trouble to developers (issues will be notified to developers via email). Please move to https://github.com/vietnh1009/ASCII-generator/issues/25 to discuss this matter and close this issue.
