### ISSUE TITLE
何同学 is a thief！！

### ISSUE THREAD

**Issue by GISWLH** [vietnh1009/ASCII-generator#54]
The author made a lot of contributions, but 何同学 made a profit by deleting the name of the original author, which seriously violated the MIT open source agreement. 何同学 may make a profit of hundreds of thousands of dollars.

**Comment by simidagogogo** [comment]
怎么大家都过来围观了，这动静好大

**Comment by huanli233** [comment]
您的 Issue 不符合 GitHub Community Code of Conduct 的精神，重复的内容可能会打扰到开发者并给开发者带来困扰（Issue 会通过 email 通知开发者）
请转移到 https://github.com/vietnh1009/ASCII-generator/issues/25 去讨论此事，并关闭此 Issue
Your issue does not comply with the spirit of the GitHub Community Code of Conduct. Duplicate content may disturb and cause trouble to developers (issues will be notified to developers via email). Please move to https://github.com/vietnh1009/ASCII-generator/issues/25 to discuss this matter and close this issue.

**Comment by CyanChanges** [comment]
@vietnh1009 may you close this too?
